project/urls.py
from django.urls import reverse_lazy, path
from django.views.generic import RedirectView
from j2fa.views import TwoFactorAuth
from django.contrib import admin


urlpatterns = [
    path("admin/", admin.site.urls),
    path("2fa/", TwoFactorAuth.as_view(), name="j2fa-obtain-auth"),
    path("", RedirectView.as_view(url=reverse_lazy("admin:login"))),
]

j2fa/models.py
import logging
from django.contrib.auth.models import User
from django.db import models
from django.conf import settings
from django.utils.timezone import now
from j2fa.helpers import j2fa_make_code

logger = logging.getLogger(__name__)


class TwoFactorSession(models.Model):
    created = models.DateTimeField(default=now, db_index=True, blank=True)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, related_name="+", on_delete=models.CASCADE)
    user_agent = models.CharField(max_length=512)
    ip = models.GenericIPAddressField(db_index=True)
    phone = models.CharField(max_length=32, db_index=True)
    email = models.EmailField(blank=True, default="")
    code = models.CharField(max_length=8, default=j2fa_make_code, blank=True)
    active = models.BooleanField(default=False, db_index=True, blank=True)
    archived = models.BooleanField(default=False, db_index=True, blank=True)

    def __str__(self):
        return "[{}]".format(self.id)

    @staticmethod
    def check_ip(ip_a: str, ip_b: str) -> bool:
        """
        Only compares first 2 parts of the IP address to avoid issues with frequently changing IPs.
        :param ip_a:
        :param ip_b:
        :return: bool
        """
        return ip_a.split(".")[:2] == ip_b.split(".")[:2]

    def activate(self):
        self.active = True
        self.archived = False
        self.save()
        TwoFactorSession.objects.all().filter(user=self.user).exclude(id=self.id).update(archived=True, active=False)

    def is_valid(self, user: User, ip: str, user_agent: str) -> bool:
        return self.user == user and self.check_ip(self.ip, ip) and self.user_agent[:512] == user_agent[:512]

j2fa/forms.py
from django import forms
from django.utils.translation import gettext_lazy as _


class TwoFactorForm(forms.Form):
    code = forms.CharField(label=_("two.factor.code.label"), max_length=8, min_length=1)

j2fa/views.py
import logging
from datetime import timedelta, datetime
from typing import List, Tuple, Union
from django.conf import settings
from ipware.ip import get_client_ip  # type: ignore  # pytype: disable=import-error
from j2fa.errors import TwoFactorAuthError
from j2fa.forms import TwoFactorForm
from j2fa.models import TwoFactorSession
from j2fa.helpers import j2fa_make_code, j2fa_phone_filter, j2fa_send_sms
from django.contrib.auth.models import User
from django.core.exceptions import ValidationError
from django.http import HttpRequest
from django.shortcuts import render, redirect
from django.urls import reverse
from django.utils.timezone import now
from django.utils.translation import gettext as _
from django.views.generic import TemplateView
from django.core.mail import send_mail

logger = logging.getLogger(__name__)


class TwoFactorAuth(TemplateView):
    template_name = "j2fa/ask-code2.html"
    logout_view_name = "admin:logout"
    default_next_view_name = "admin:index"
    max_failed_attempts = 5
    max_failed_attempts_hours = 24
    code_expires_seconds = 300

    def get_user_email(self, user: User) -> str:
        """
        Allow user-specific customization of email address to receive the 2FA code.
        Return empty string if user is not supposed to get codes via email but email sending is enabled (J2FA_SEND_TO_EMAIL=True).
        :param user: User
        :return: Email address (if email should be used to send the code, empty otherwise)
        """
        return user.email

    def get_user_phone(self, user: User) -> str:
        """
        Returns User's phone number. By default uses User.profile.phone.
        :param user: User
        :return: str
        """
        if user.is_authenticated and hasattr(user, "profile") and hasattr(user.profile, "phone"):  # type: ignore
            return user.profile.phone  # type: ignore
        return ""

    def make_2fa_code(self) -> str:
        """
        Makes 2FA code.
        By default makes 4-6 digit integer code as str.
        :return: str
        """
        return j2fa_make_code()

    def get_context_data(self, **kw):
        request = self.request
        assert isinstance(request, HttpRequest)

        next_url = request.POST.get("next") if request.POST else None
        if not next_url:
            next_url = request.GET.get("next")
        if not next_url:
            next_url = request.META.get("HTTP_REFERER")
        if not next_url:
            next_url = reverse(self.default_next_view_name)

        cx = {
            "form": TwoFactorForm(data=request.POST or None),
            "next": next_url,
        }
        for k, v in kw.items():
            if v:
                cx[k] = v
        return cx

    def get(self, request, *args, **kwargs):
        user = request.user
        if not user.is_authenticated:
            return redirect(self.logout_view_name)

        cx = self.get_context_data()
        try:
            ses = self.get_session(request)
            channel = request.GET.get("channel") or ""
            next_path = request.GET.get("next") or ""
            if channel:
                self.send_code(ses, channel=channel)
                return redirect(reverse("j2fa-obtain-auth") + f"?msg-resent={channel}&next={next_path}")
            msg_resent = request.GET.get("msg-resent") or ""
            if msg_resent:
                cx["info"] = _("msg.resent")
                cx["alt_channel"] = "I" if msg_resent == "M" else "M"
        except ValidationError as e:
            cx["error"] = " ".join(e.messages)

        return render(request, self.template_name, cx)

    def count_failed_attempts(self, user, since: datetime) -> int:
        return TwoFactorSession.objects.all().filter(user=user, created__gt=since, archived=False).count()

    def send_sms_code(self, phone: str, msg: str, channel: str = "") -> int:
        """
        Send SMS code.
        Args:
            phone: str
            msg: str
            channel: str

        Returns:
            HTTP response status, >300 on error.
        """
        res = j2fa_send_sms(phone, msg, channel=channel)
        return res.status_code

    def send_email_code(
        self, subject: str, body: str, sender: Union[str, Tuple[str, str]], recipient_list: List[Union[str, Tuple[str, str]]], fail_silently: bool = False
    ):
        """
        Emails the OTP code
        Args:
            subject:
            body:
            sender:
            recipient_list:
            fail_silently:

        Returns:
            None
        """
        send_mail(subject, body, sender, recipient_list, fail_silently=fail_silently)

    def send_code(self, ses: TwoFactorSession, channel: str = ""):
        logger.info("2FA: %s -> '%s' (%s) %s", ses.code, ses.phone, ses.user, channel)
        send_by_email = hasattr(settings, "J2FA_SEND_TO_EMAIL") and settings.J2FA_SEND_TO_EMAIL and ses.email
        if settings.SMS_TOKEN and ses.phone:
            status_code = self.send_sms_code(ses.phone, ses.code, channel=channel)
            if status_code >= 300 and hasattr(settings, "EMAIL_HOST") and settings.EMAIL_HOST:
                logger.warning("SMS sending failed to %s (%s), trying to send code by email", ses.phone, ses.user)
                send_by_email = settings.J2FA_FALLBACK_TO_EMAIL if hasattr(settings, "J2FA_FALLBACK_TO_EMAIL") else False
        if send_by_email:
            logger.info("2FA (email): %s -> %s (%s)", ses.code, ses.email, ses.user)
            subject = settings.SMS_SENDER_NAME + ": " + _("One time login code")
            body = _("j2fa.code.email.body").format(code=ses.code)
            sender = settings.DEFAULT_FROM_EMAIL
            recipient = ses.email
            self.send_email_code(subject, body, sender, [recipient], fail_silently=False)

    def get_session(self, request: HttpRequest, force: bool = False) -> TwoFactorSession:
        user, ip, user_agent, phone, email = self.get_session_const(request)
        ses_id = request.session.get("j2fa_session")
        ses = TwoFactorSession.objects.filter(id=ses_id).first() if ses_id else None
        assert ses is None or isinstance(ses, TwoFactorSession)
        time_now = now()
        if not ses or not ses.is_valid(user, ip, user_agent) or force or time_now - ses.created > timedelta(seconds=self.code_expires_seconds):
            since = time_now - timedelta(hours=self.max_failed_attempts_hours)
            if self.count_failed_attempts(user, since) > self.max_failed_attempts:
                raise TwoFactorAuthError(_("too.many.failed.attempts"))

            ses = TwoFactorSession.objects.create(
                user=user,
                ip=ip,
                user_agent=user_agent[:512],
                phone=phone,
                email=email,
                code=self.make_2fa_code(),
            )
            assert isinstance(ses, TwoFactorSession)
            self.send_code(ses)
            request.session["j2fa_session"] = ses.id
        return ses

    def get_session_const(self, request: HttpRequest):
        user = request.user
        ip = get_client_ip(request)[0]
        if ip is None and settings.DEBUG:
            ip = "127.0.0.1"
        user_agent = str(request.META["HTTP_USER_AGENT"])[:512]
        phone = j2fa_phone_filter(self.get_user_phone(user))  # type: ignore
        email = self.get_user_email(user)  # type: ignore
        if not phone:
            raise TwoFactorAuthError(_("your.phone.number.missing.from.system"))
        return user, ip, user_agent, phone, email

    def post(self, request, *args, **kwargs):  # pylint: disable=unused-argument
        cx = self.get_context_data()
        form = cx["form"]
        assert isinstance(form, TwoFactorForm)

        if form.is_valid():
            try:
                ses = self.get_session(request)
                assert isinstance(ses, TwoFactorSession)
                code = form.cleaned_data["code"]
                user, ip, user_agent, phone, email = self.get_session_const(request)
                logger.info("2FA: Post %s %s %s %s %s vs %s", user, ip, user_agent, phone, email, ses.code)
                if ses.code != code:
                    code_expire_time_s = self.code_expires_seconds
                    if code_expire_time_s > 0 and code:
                        time_now = now()
                        old = time_now - timedelta(seconds=code_expire_time_s)
                        recent = (
                            TwoFactorSession.objects.filter(created__gte=old, user=user, ip=ip, user_agent=user_agent[:512], code=code, archived=False)
                            .order_by("-id")
                            .first()
                        )
                        if recent is not None:
                            assert isinstance(recent, TwoFactorSession)
                            logger.info("2FA: Passing %s as code %s matches %s (age %s)", user, code, recent, time_now - recent.created)
                        else:
                            self.get_session(request, force=True)
                            raise TwoFactorAuthError(_("Invalid code, sending a new one."))
                    else:
                        self.get_session(request, force=True)
                        raise TwoFactorAuthError(_("Invalid code, sending a new one."))
                logger.info("2FA: Pass %s / %s", user, ses)
                ses.activate()

                return redirect(cx.get("next"))
            except TwoFactorAuthError as exc:
                form.add_error(None, exc)
            except Exception as exc:
                form.add_error(None, exc)

        return render(request, self.template_name, cx)

j2fa/templates/j2fa/ask-code.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% load static i18n %}

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>{% trans '2-Factor Authentication' %}</title>

    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
    <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
    <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->

    {% block head_end %}{% endblock %}
</head>
<body>

{% block body %}

<div style="font-family: Courier">

    <h1 style="font-size: 1.5em;">{% trans '2-Factor Authentication' %}</h1>

    {% if error %}
    <div style="color: red; margin-bottom: 1em;">
        {{ error }}
    </div>
    {% endif %}

    <form style="font-family: Courier;" action="" method="post" role="form">{% csrf_token %}
        {{ form }}
        <button class="btn btn-lg btn-success btn-block" type="submit" value="login">{% trans 'Continue' %}</button>
        <input type="hidden" name="next" value="{{ next }}"/>
    </form>

    <p style="padding-top: 1em;">
        <a href="{% url 'admin:logout' %}">{% trans 'Logout' %}</a>
    </p>

</div>

{% endblock %}

{% block body_end %}{% endblock %}

</body>
</html>

j2fa/templates/j2fa/ask-code1.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% load static i18n %}

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>{% trans '2-Factor Authentication' %}</title>

    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
    <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
    <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->

    {% block head_end %}{% endblock %}
</head>
<body>

{% block body %}

<div style="font-family: Courier">

    <h1 style="font-size: 1.5em;">{% trans '2-Factor Authentication' %}</h1>

    {% if error %}
    <div style="color: red; margin-bottom: 1em;">
        {{ error }}
    </div>
    {% endif %}

    <form style="font-family: Courier;" action="" method="post" role="form">{% csrf_token %}
        {{ form }}
        <button class="btn btn-lg btn-success btn-block" type="submit" value="login">{% trans 'Continue' %}</button>
        <input type="hidden" name="next" value="{{ next }}"/>
    </form>

    <p style="padding-top: 1em;">
        <a href="{% url 'admin:logout' %}">{% trans 'Logout' %}</a>
    </p>

</div>

{% endblock %}

{% block body_end %}{% endblock %}

</body>
</html>

j2fa/templates/j2fa/ask-code2.html
<!DOCTYPE html>
<html lang="fi">
<head>
    {% load static i18n %}

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>{% trans '2-Factor Authentication' %}</title>

    <!-- Bootstrap Core CSS -->
    <link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" rel="stylesheet">
    <style>
        .login-panel {
          margin-top: 25%;
        }
    </style>

    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
    <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
    <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->
</head>
<body>


<div class="container">
    <div class="row">
        <div class="col-md-4 col-md-offset-4">
            <div class="login-panel panel panel-default">
                <div class="panel-heading">
                    <h3 class="panel-title">{% trans '2-Factor Authentication' %}</h3>
                </div>
                <div class="panel-body">

                    <form action="" method="post" role="form">
                        {% csrf_token %}
                        <fieldset>
                            {% if info %}
                                <div class="alert alert-success">
                                    <p class="form-error">{{ info }}</p>
                                </div>
                            {% endif %}
                            {% if form.non_field_errors or form.code.errors or error %}
                                <div class="alert alert-danger">
                                    <!--<a class="close" data-dismiss="alert">&times;</a>-->
                                    {% if error %}
                                        <p class="form-error">{{ error }}</p>
                                    {% endif %}
                                    {% for err in form.non_field_errors %}
                                        <p class="form-error">{{ err }}</p>
                                    {% endfor %}
                                    {% if form.code.errors %}
                                        <p class="form-error">({{ form.code.label }}) {{ form.code.errors }}</p>
                                    {% endif %}
                                </div>
                            {% endif %}
                            <div class="form-group">
                                <label class="control-label  " for="id_code">{% trans 'two.factor.code.label' %}</label>
                                <div class=" ">
                                    <input type="tel" name="code" class="form-control" required id="id_code" />
                                </div>
                            </div>
                        </fieldset>
                        <button class="btn btn-lg btn-success btn-block" type="submit" value="login">{% trans 'Continue' %}</button>
                        <input type="hidden" name="next" value="{{ next }}"/>
                    </form>

                    <div style="margin-top:1em;">
                        <a href="{% url 'j2fa-obtain-auth' %}?channel={{ alt_channel|default:"M" }}&next={{ next }}">{% trans 'sms.not.received.text' %}</a>
                        | <form id="logout-form" method="post" action="{% url 'admin:logout' %}" style="display: inline-block;" >
                              {% csrf_token %}
                              <button class="btn btn-link" type="submit">{% translate "Logout" %}</button>
                          </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>


</body>
</html>